@extends('layouts.public')
@section('title', __('news.title').' · '.setting('site_name'))
@section('description', __('news.description'))
@section('content')
<section class="bg-primary-container py-xl"><div class="mx-auto max-w-container-max px-margin-mobile md:px-gutter"><nav class="mb-sm text-caption text-on-primary-container"><a href="{{ lroute('home') }}">{{ __('common.nav.home') }}</a> / {{ __('news.title') }}</nav><h1 class="font-display text-display-lg-mobile text-on-primary md:text-display-lg">{{ __('news.title') }}</h1><p class="mt-xs max-w-2xl text-body-lg text-on-primary/90">{{ __('news.description') }}</p></div></section>
<div class="mx-auto max-w-container-max px-margin-mobile py-xl md:px-gutter">
    <form method="GET" class="mb-lg grid gap-xs rounded-xl border border-outline-variant/40 bg-surface-container-lowest p-sm ambient-shadow md:grid-cols-[1fr_16rem_auto]"><input name="q" value="{{ request('q') }}" placeholder="{{ __('news.search') }}" class="min-h-11 rounded-lg border border-outline-variant px-sm"><select name="category" class="min-h-11 rounded-lg border border-outline-variant px-sm"><option value="">{{ __('news.all_categories') }}</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected(request('category') === $category->slug)>{{ $category->name }} ({{ $category->posts_count }})</option>@endforeach</select><button class="rounded-lg bg-primary-container px-md text-on-primary">{{ __('properties.filters.apply') }}</button></form>
    @if($featured && !request()->hasAny(['q','category']))<article class="mb-xl grid overflow-hidden rounded-xl bg-primary-container ambient-shadow md:grid-cols-2">@if($featured->featured_image)<img src="{{ Storage::url($featured->featured_image) }}" alt="{{ $featured->title }}" class="h-full min-h-72 w-full object-cover">@endif<div class="flex flex-col justify-center p-lg"><span class="mb-xs text-caption uppercase tracking-wider text-on-secondary-container">{{ __('news.featured') }}</span><h2 class="font-display text-headline-lg text-on-primary">{{ $featured->title }}</h2><p class="mt-sm text-body-md text-on-primary/80">{{ $featured->excerpt }}</p><a href="{{ lroute('news.show', ['slug' => $featured->slug]) }}" class="mt-md inline-flex min-h-11 items-center text-on-secondary-container">{{ __('news.read_more') }}</a></div></article>@endif
    <div class="grid gap-gutter md:grid-cols-2 lg:grid-cols-3">
        @forelse($posts as $post)<article class="overflow-hidden rounded-xl border border-outline-variant/40 bg-surface-container-lowest ambient-shadow hover-lift">@if($post->featured_image)<img src="{{ Storage::url($post->featured_image) }}" alt="{{ $post->title }}" class="h-52 w-full object-cover" loading="lazy">@endif<div class="p-md"><div class="mb-xs flex gap-xs text-caption text-on-surface-variant"><span>{{ $post->category?->name }}</span><span>{{ __('news.minutes', ['count' => $post->reading_time]) }}</span></div><h2 class="text-title-lg text-on-surface"><a href="{{ lroute('news.show', ['slug' => $post->slug]) }}" class="hover:text-secondary">{{ $post->title }}</a></h2><p class="mt-xs line-clamp-3 text-body-md text-on-surface-variant">{{ $post->excerpt }}</p></div></article>@empty<div class="rounded-xl bg-surface-container-low p-xl text-center md:col-span-2 lg:col-span-3">{{ __('news.empty') }}</div>@endforelse
    </div>
    <div class="mt-lg">{{ $posts->links() }}</div>
</div>
@endsection
